server:
  port: 8080
  servlet:
    context-path: /vadhyaronline

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vadhyaronline?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: dev
    password: DevP@ssw0rd
  jpa:
    show-sql: true
    hibernate.ddl: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
