server:
  port: 8080
  servlet:
    context-path: /vadhyar

spring:
  datasource:
    url: jdbc:postgresql://vadhyar.c2ekvuk7fhvc.ap-south-1.rds.amazonaws.com:5432/vadhyar
    driverClassName: org.postgresql.Driver
    username: root
    password: Sudhu1992
    hikari:
      maximum-pool-size: 4
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL91Dialect
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  jackson:
    default-property-inclusion: non_null
  cache:
    cache-names: restApiAuthTokenCache,LoginUsers

management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:4200/
        allowed-methods: GET,POST,PUT,DELETE
