server:
  port: 8080
  servlet:
    context-path: /vadhyar

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:vadhyar
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: vadhyardev
    password: VadhyarDev123
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle12cDialect
  h2:
    console:
      enabled: true
      path: /console
  jackson:
    default-property-inclusion: non_null
  cache:
    cache-names: restApiAuthTokenCache
