server:
  port: 8080
  servlet:
    context-path: /vadhyar

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/vadhyardev
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: devuser
    password: DevUser123
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.Oracle12cDialect
  jackson:
    default-property-inclusion: non_null
  cache:
    cache-names: restApiAuthTokenCache

management:
  endpoints:
    web: 
      cors:
        allowed-origins: http://localhost:4200/
        allowed-methods: GET,POST,PUT,DELETE
